name: 'Lint VBA'
description: 'Test VBA source code.'
branding:
  icon: "sun"
  color: "red"
inputs:
  source_path:
    description: 'Path to source files.'
    default: "./src"
  test_path:
    description: 'Path to test files.'
    default: "./tests"
  github_token:
    description: 'coveralls repo token'
runs:
  using: "composite"
  steps:
    - run: |
        python -m pip install pip --upgrade
        python -m pip install setuptools --upgrade
        python -m pip install git+https://github.com/Beakerboy/vbaUnit.git@Coverage
      shell: bash
    - env:
        SOURCEPATH: "{{ inputs.source_path }}"
        TESTPATH: "{{ inputs.test_path }}"
        COVERALLS_REPO_TOKEN: "{{ inputs.github_token }}"
      run: |
        python -m vba_unit --coverage
      shell: bash
